### PR TITLE
Added synology photos api

### PR DESCRIPTION
**Pull request by lodesmets**
These commits adds functions to get albums and images from synology photos. I will use these in home assistant to add synology photos to the media browser

### CODE REVIEW

**Comment by lodesmets** [comment]
@mib1185 can you take a look at this?

**Comment by mib1185** [comment]
hi @lodesmets 
first, many thanks for your contribution 👍 
I did not forget you but be very busy at the moment.
I'll try to review this PR upcoming week, meanwhile, please add tests for this new feature.

thx

**Comment by lodesmets** [comment]
> hi @lodesmets first, many thanks for your contribution 👍 I did not forget you but be very busy at the moment. I'll try to review this PR upcoming week, meanwhile, please add tests for this new feature. Further, I would highly recommend to use the VScode dev-container on this project, since it implementes a automatic code formatting.
> 
> thx

Hi,

Yeah I didn't want to seem impatient.  But I previously committed this code to the Hacs_fr repo of this, so I didn't know which one was the actively maintained one

**Comment by lodesmets** [comment]
Bump

**Comment by mib1185** [comment]
hi @lodesmets 
Sorry for the (_very_) late reply, but I haven't found time due to other priorities.
I have started testing this today, but still need some more time to get and test it.

**Comment by lodesmets** [comment]
> hi @lodesmets Sorry for the (_very_) late reply, but I haven't found time due to other priorities. I have started testing this today, but still need some more time to get and test it.

No problem. The thing I want to use this for is a project I'm going to do in summer 2023. So take your time

**Comment by lodesmets** [comment]
Hey,
Have you found some time to look at this?

**Comment by mib1185** [comment]
Hi @lodesmets 
sorry, but unfortunately not yet :confused: but i'll work my way into it now

**Comment by mib1185** [comment]
@lodesmets if it is ok for you, I would like to rework this PR, with following topics in mind
- rebase to current state (_the lib was lately rewritten to use aiohttp see #221_)
- introduce models to this Synology Photos module

**Review by mib1185 — COMMENTED** [review]
open todos
[ ] find a "better" way to get the thumbnail url
[ ] complete tests

**Comment by lodesmets** [comment]
Hey, thanks for the responses.

Yeah i know i have done some weird things to get the thumbnail url. But this is an anoying thing by home assistant. The thumbnail needs to be an url

**Comment by mib1185** [comment]
@lodesmets i think these are enough unit tests for now. may i ask you to do some manual tests and check if everything works as expected?

**Comment by lodesmets** [comment]
@mib1185 Hey, I tested it with HA and it looks great. 
I had to make some slight changes to my HA implementation, to make it compatible with your changes

**Comment by lodesmets** [comment]
Once you release the new version of this library, I will tag you in my PR of home assistant, OK?

**Comment by mib1185** [comment]
I'm going to merge this now, but release of 2.1.0 will not be done now, because there are some open tasks which i would like to have in 2.1 (_at least #237 and #231_)

**Pull request merged**
