### PR TITLE
Guard expensive debug logging with isEnabledFor

### PR DESCRIPTION
**Pull request by bdraco**
Note that update_query rebuilds the whole query string every time so it would be a bit cleaner to call it once, however its probably not worth optimizing if its only going to be called when debug is on now

### CODE REVIEW

**Comment by mib1185** [comment]
the failing tests are not related - since yarl 1.9.5 (_with 1.9.4 it is working_) the url does not contain the https default port 443 anymore (_expected `https://nas.mywebsite.me:443` got `https://nas.mywebsite.me`_)

**Comment by mib1185** [comment]
hi @bdraco , the tests are fixed now, please rebase your branch, thx :+1:

**Comment by bdraco** [comment]
Thanks @mib1185 Should be all set now

**Review by mib1185 — APPROVED** [review]
Thanks @bdraco :+1:

**Pull request merged**
